### ISSUE TITLE
Download Link Points to Localhost

### ISSUE THREAD

**Issue by yatrix7** [nnja/python#45]
The "download them here" link on https://www.learnpython.dev/03-intermediate-python/80-web-frameworks/final-exercise/ points to localhost. 

Great course! Really enjoyed it.

**Comment by archeranimesh** [comment]
Hope [this](https://github.com/nnja/python/pull/48) pull request if approved with solve the issue.

**Comment by nnja** [comment]
Thank you for pointing this out, it's fixed in #94
