### ISSUE TITLE
Thank you Nina!

### ISSUE THREAD

**Issue by cecilphillip** [nnja/python#59]
We've been using this course for our Python Live stream on Twitch. Creating this issue just for our audience to share some ❤️

**Comment by emilpriver** [comment]
Thank you Nina for you awesome course! 

1 think that could be interesting for your course: Django with Rest Framework :D

**Comment by thedamian** [comment]
Thank you Nina for a great course for free! You rock!

**Comment by clarkio** [comment]
Thank you Nina!!!!

![bitmoji](https://render.bitstrips.com/v2/cpanel/f70171d9-4f76-4409-b78f-8ed9b0076e12-1af5294e-37d3-4206-9bf6-d21903386d2f-v1.png?transparent=1&palette=1&width=246)

**Comment by levep** [comment]
Thank you Nina!!
