### ISSUE TITLE
Single lesson not showing Checkmark

### ISSUE THREAD

**Issue by martin-martin** [nnja/python#80]
This is very low priority, but I thought I leave a note in case it's helpful : )

The lesson [Function Arguments](https://www.learnpython.dev/02-introduction-to-python/060-functions/30-function-arguments/) (`30-function-arguments.md`) doesn't display a checkmark on the front-end, also after being visited:

![image](https://user-images.githubusercontent.com/12371494/93598461-5baa9180-f9c5-11ea-8727-ce869c5de589.png)

It also (temporarily) removes all the checkmarks that exist on other lessons, while it's selected:

![image](https://user-images.githubusercontent.com/12371494/93598532-77ae3300-f9c5-11ea-9784-c4202c1cf7bb.png)

Not sure why, thought I'd leave a note ¯\_(ツ)_/¯ 

Thanks for the course materials!

**Comment by nnja** [comment]
That's a weird bug! I don't have time to troubleshoot the template at the moment, but I appreciate you taking the time to report it.

**Comment by nnja** [comment]
Fixed by @hangindev (thanks!) and merged in #97
